apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-rcc-manager
  namespace: rcc-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daniland.t@gmail.com
    privateKeySecretRef: 
      name: letsencrypt-rcc-manager
    solvers:
    - http01:
        ingress:
          class: nginx
