apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal-custom.override: |
    rewrite stop {
      name regex (.*)\.danweb\.com\.$ {1}.default.svc.cluster.local.
      answer name (.*).\default\.svc\.cluster\.local\.$ {1}.danweb.com.
    }