apiVersion: v1
kind: Service
metadata:
  name: rcc-manager-service
  namespace: rcc-manager
  labels:
    app: rcc-manager-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: rcc-manager-api