apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy1
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql-app
  template:
    metadata:
      labels:
        app: mssql-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        securityContext:
          privileged: true
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "RccManager@2023"
        volumeMounts:
        - name: mssql-mount1
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-mount1
        persistentVolumeClaim:
          claimName: mssql-data1